# Generated by Django 3.2 on 2022-10-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_mailing_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='plase',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
