# Generated by Django 3.2 on 2022-11-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_devicesstatisticcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cost',
            field=models.PositiveSmallIntegerField(default=65),
            preserve_default=False,
        ),
    ]
