version: '2.11.2'

services:
  web:
    # build: ./app
    build: .
    command: python manage.py runserver 0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A KINOCMS_proj worker -l info
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data: