# Generated by Django 3.2 on 2022-10-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20221009_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='total_booked',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='total_bought',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
