# Generated by Django 3.2 on 2022-10-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20221011_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='total_booked',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='total_bought',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
