# Generated by Django 3.2 on 2022-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_auto_20221026_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_movie_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_movie_uk',
            field=models.TextField(null=True),
        ),
    ]
