# Generated by Django 3.2 on 2022-11-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20221106_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowCost',
        ),
    ]
