# Generated by Django 3.2 on 2022-11-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_delete_showcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='cost',
            field=models.PositiveSmallIntegerField(default=120),
            preserve_default=False,
        ),
    ]
