# Generated by Django 3.2 on 2022-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='template',
            field=models.FileField(blank=True, upload_to='mailing_templates/'),
        ),
    ]
