# Generated by Django 3.2 on 2022-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='town',
            field=models.CharField(default='Kiev', max_length=50),
            preserve_default=False,
        ),
    ]
