# Generated by Django 3.2 on 2022-10-03 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_mailing_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
