# Generated by Django 3.2 on 2022-09-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220924_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='letter_name',
        ),
    ]
