# Generated by Django 3.2 on 2022-10-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_ticket_plase'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesStatisticCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('device_type', models.CharField(choices=[('mobile', 'Мобільний телефон або смартфон'), ('tablet_and_other_sensor_devices', 'Планшети та інщі сенсорні пристрої'), ('pc', 'Компьютер, або ноутбук')], max_length=120)),
                ('number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
