# Generated by Django 3.2 on 2022-07-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_cinema', models.CharField(max_length=30)),
                ('description_cinema', models.TextField()),
                ('conditions_cinema', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_cinema_hall', models.SmallIntegerField()),
                ('description_cinema_hall', models.TextField()),
                ('schema_hall', models.ImageField(upload_to='')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=150)),
                ('description_movie', models.TextField()),
                ('url_to_trailer', models.URLField()),
                ('type_2d', models.BooleanField(default=True)),
                ('type_3d', models.BooleanField(default=False)),
                ('type_IMAX', models.BooleanField(default=False)),
                ('movie_distribution_start', models.DateField(blank=True, null=True)),
                ('movie_distribution_finish', models.DateField(blank=True, null=True)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('music_by', models.CharField(blank=True, max_length=50, null=True)),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('screen_by', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('budget', models.CharField(blank=True, max_length=20, null=True)),
                ('age_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('runing_time', models.CharField(blank=True, max_length=50, null=True)),
                ('cinema', models.ManyToManyField(to='cinema.Cinema')),
                ('image_galery', models.ManyToManyField(related_name='movie_image_galery', to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
            ],
        ),
        migrations.CreateModel(
            name='SeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_seo', models.URLField()),
                ('title_seo', models.CharField(max_length=200)),
                ('keyword_seo', models.TextField()),
                ('description_seo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_show', models.DateField()),
                ('time_show', models.TimeField()),
                ('total_booked', models.JSONField()),
                ('total_bought', models.JSONField()),
                ('cinema_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinemahall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ShowCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('Show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.show')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.seoblock'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image_galery',
            field=models.ManyToManyField(related_name='cinemahall_image_galery', to='cinema.Galery'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='image_top_banner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery'),
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image_galery',
            field=models.ManyToManyField(related_name='cinema_image_galery', to='cinema.Galery'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='image_top_banner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cinema_image_top_banner', to='cinema.galery'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
        migrations.CreateModel(
            name='BannerWithTimeScrolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timescrolling', models.SmallIntegerField()),
                ('text', models.TextField(null=True)),
                ('image', models.ManyToManyField(to='cinema.Galery')),
            ],
        ),
    ]
