# Generated by Django 3.2 on 2022-08-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='image',
            field=models.ImageField(default='time_text', upload_to='galery/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
