# Generated by Django 3.2 on 2022-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercell',
            name='purpose',
            field=models.CharField(choices=[('highest_banner', 'баннер на верхней части страницы'), ('banner_news_and_promotions', 'баннер про новости и акции')], default='highest_banner', max_length=50),
            preserve_default=False,
        ),
    ]
