# Generated by Django 3.2 on 2022-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_galery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerwithtimescrolling',
            name='timescrolling',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bannerwithtimescrolling',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
