# Generated by Django 3.2 on 2022-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_bannercell_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromotionsAndNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_of_status', models.BooleanField(default=True)),
                ('timescrolling', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
