# Generated by Django 3.2 on 2022-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20220809_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerwithtimescrolling',
            old_name='image',
            new_name='galery',
        ),
    ]
