# Generated by Django 3.2 on 2022-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_bannerpromotionsandnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(blank=True, upload_to='galery/', verbose_name='Изображения'),
        ),
    ]
