# Generated by Django 3.2 on 2022-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20221018_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_movie_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_movie_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_movie_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_movie_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_movie_de',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_movie_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_movie_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_movie_uk',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
