# Generated by Django 3.2 on 2022-08-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_rename_image_bannerwithtimescrolling_galery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerwithtimescrolling',
            name='galery',
            field=models.ManyToManyField(default='EMPTY_BANNER', to='cinema.Galery'),
        ),
    ]
