# Generated by Django 3.2 on 2022-08-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_bannerwithtimescrolling_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('text', models.TextField(null=True)),
                ('galery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.galery')),
            ],
        ),
        migrations.CreateModel(
            name='HighestBannerWithTimeScrolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_of_status', models.BooleanField(default=True)),
                ('timescrolling', models.SmallIntegerField(null=True)),
                ('banner_cell', models.ManyToManyField(to='cinema.BannerCell')),
            ],
        ),
        migrations.DeleteModel(
            name='BannerWithTimeScrolling',
        ),
    ]
