# Generated by Django 3.2 on 2022-09-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_movie_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.galery'),
        ),
    ]
