# Generated by Django 3.2 on 2022-09-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_movie_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='seo_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
    ]
