# Generated by Django 3.2 on 2022-08-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_auto_20220827_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercell',
            name='text',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
