# Generated by Django 3.2 on 2022-09-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_movie_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='conditions_cinema',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image_galery',
            field=models.ManyToManyField(null=True, related_name='cinema_image_galery', to='cinema.Galery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image_top_banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cinema_image_top_banner', to='cinema.galery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.galery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.galery'),
        ),
    ]
