# Generated by Django 3.2 on 2022-08-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_alter_highestbannerwithtimescrolling_on_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercell',
            name='galery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.galery'),
        ),
    ]
