# Generated by Django 3.2 on 2022-09-11 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20220910_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='number_cinema_hall',
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='cinema_hall_name',
            field=models.CharField(default='defailt_name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinemahall',
            name='created_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cinema',
            name='image_galery',
            field=models.ManyToManyField(related_name='cinema_image_galery', to='cinema.Galery'),
        ),
    ]
