# Generated by Django 3.2 on 2022-09-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_auto_20220911_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='schema_hall',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
