# Generated by Django 3.2 on 2022-08-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_bannercell_galery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercell',
            name='galery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cinema.galery'),
        ),
        migrations.AlterField(
            model_name='highestbannerwithtimescrolling',
            name='banner_cell',
            field=models.ManyToManyField(blank=True, null=True, to='cinema.BannerCell'),
        ),
        migrations.AlterField(
            model_name='highestbannerwithtimescrolling',
            name='on_of_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='highestbannerwithtimescrolling',
            name='timescrolling',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
