# Generated by Django 3.2 on 2022-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_auto_20220828_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercell',
            name='galery',
        ),
        migrations.AddField(
            model_name='bannercell',
            name='image',
            field=models.ImageField(default='234', upload_to='galery/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
