# Generated by Django 3.2 on 2022-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_alter_cinemahall_schema_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='on_of_status',
            field=models.BooleanField(default=False),
        ),
    ]
