# Generated by Django 3.2 on 2022-09-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_cinema_on_of_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='image_top_banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.galery'),
        ),
    ]
