# Generated by Django 3.2 on 2022-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_auto_20220829_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highestbannerwithtimescrolling',
            name='on_of_status',
            field=models.BooleanField(default=True),
        ),
    ]
