# Generated by Django 3.2 on 2022-09-12 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_cinemahall_image_top_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemahall',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
    ]
