# Generated by Django 3.2 on 2022-08-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_highestbannerwithtimescrolling_on_of_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThroughBackroundBannerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(choices=[('background_photo', 'фото на фоне'), ('simple_photo', 'просто фото')], default='simple_photo', max_length=30)),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.galery')),
            ],
        ),
    ]
