# Generated by Django 3.2 on 2022-08-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_throughbackroundbannerform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throughbackroundbannerform',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.galery'),
        ),
    ]
