# Generated by Django 3.2 on 2022-08-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_throughbackroundbannerform_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThroughBackroundBannerForm',
            new_name='ThroughBackroundBanner',
        ),
    ]
