# Generated by Django 3.2 on 2022-08-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_rename_throughbackroundbannerform_throughbackroundbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='throughbackroundbanner',
            old_name='phone',
            new_name='background',
        ),
    ]
