# Generated by Django 3.2 on 2022-08-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_rename_phone_throughbackroundbanner_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='special_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
