# Generated by Django 3.2 on 2022-10-09 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20221009_1211'),
        ('pages', '0002_auto_20221009_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock'),
        ),
    ]
