# Generated by Django 3.2 on 2022-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_mainpage_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandpromotions',
            name='title_news_or_promo',
            field=models.CharField(max_length=300),
        ),
    ]
