# Generated by Django 3.2 on 2022-10-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20221018_1101'),
        ('pages', '0006_auto_20221023_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='logo',
        ),
        migrations.CreateModel(
            name='ContactCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
            ],
        ),
    ]
