# Generated by Django 3.2 on 2022-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
