# Generated by Django 3.2 on 2022-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20221106_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
