# Generated by Django 3.2 on 2022-11-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20221106_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(default='Контакти', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_uk',
            field=models.CharField(default='Контакти', max_length=100, null=True),
        ),
    ]
