# Generated by Django 3.2 on 2022-07-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_page_seo_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news_or_promo', models.CharField(max_length=30)),
                ('description_news_or_promo', models.TextField()),
                ('date_news_or_promoptions', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('news', 'Новость'), ('promotion', 'Акция')], max_length=30)),
                ('image_galery', models.ManyToManyField(related_name='news_and_promotions_galery', to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
                ('seo_clock', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_undeleteble', models.BooleanField(default=False)),
                ('image_galery', models.ManyToManyField(to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_page_main_image', to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
    ]
