# Generated by Django 3.2 on 2022-09-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('main_page_seo_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_news_or_promo', models.CharField(max_length=30)),
                ('description_news_or_promo', models.TextField()),
                ('date_news_or_promoptions', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('publ_type', models.CharField(blank=True, choices=[('news', 'Новость'), ('promotion', 'Акция')], max_length=30)),
                ('url_to_video', models.URLField(blank=True, null=True)),
                ('image_galery', models.ManyToManyField(related_name='news_and_promotions_galery', to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_undeleteble', models.BooleanField(default=False)),
                ('special_issue', models.CharField(blank=True, choices=[('about_cinema', 'про кінотеатр'), ('cafe_bar', 'кафе-бар'), ('vip-hall', 'VIP-зала'), ('advertising', 'реклама'), ('childrens_room', 'дитяча кімната')], max_length=100, null=True)),
                ('image_galery', models.ManyToManyField(to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_page_main_image', to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('cinema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('logo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
    ]
