# Generated by Django 3.2 on 2022-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandpromotions',
            name='is_active',
            field=models.CharField(choices=[('on', 'ВКЛ'), ('off', 'ВЫКЛ')], max_length=30),
        ),
    ]
