# Generated by Django 3.2 on 2022-09-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_newsandpromotions_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsandpromotions',
            old_name='type',
            new_name='publ_type',
        ),
        migrations.RenameField(
            model_name='newsandpromotions',
            old_name='seo_clock',
            new_name='seo_block',
        ),
    ]
