# Generated by Django 3.2 on 2022-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220913_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandpromotions',
            name='publ_type',
            field=models.CharField(blank=True, choices=[('news', 'Новость'), ('promotion', 'Акция')], max_length=30),
        ),
    ]
