# Generated by Django 3.2 on 2022-09-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_newsandpromotions_publ_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandpromotions',
            name='url_to_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
