# Generated by Django 3.2 on 2022-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_newsandpromotions_url_to_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandpromotions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
