# Generated by Django 3.2 on 2022-09-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_alter_cinemahall_seo_block'),
        ('pages', '0006_alter_newsandpromotions_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_undeleteble', models.BooleanField(default=False)),
                ('special_issue', models.CharField(choices=[('about_cinema', 'про кінотеатр'), ('caf_bar', 'кафе-бар'), ('vip-hall', 'VIP-зала'), ('advertising', 'реклама'), ('childrens_room', 'дитяча реклама')], max_length=100, null=True)),
                ('image_galery', models.ManyToManyField(to='cinema.Galery')),
                ('main_image', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custom_page_main_image', to='cinema.galery')),
                ('seo_block', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cinema.seoblock')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomPage',
        ),
    ]
