# Generated by Django 3.2 on 2022-10-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20221023_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcell',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
