# Generated by Django 3.2 on 2022-09-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_custompages_special_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompages',
            name='special_issue',
            field=models.CharField(blank=True, choices=[('about_cinema', 'про кінотеатр'), ('caf_bar', 'кафе-бар'), ('vip-hall', 'VIP-зала'), ('advertising', 'реклама'), ('childrens_room', 'дитяча кімната')], max_length=100, null=True),
        ),
    ]
