# Generated by Django 3.2 on 2022-09-19 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_custompages_special_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompages',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
