# Generated by Django 3.2 on 2022-09-19 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_custompages_special_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='main page', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
