# Generated by Django 3.2 on 2022-11-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_contact_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcell',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactcell',
            name='address_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactcell',
            name='cinema_name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contactcell',
            name='cinema_name_uk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='custompages',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='custompages',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='custompages',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custompages',
            name='title_uk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsandpromotions',
            name='description_news_or_promo_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsandpromotions',
            name='description_news_or_promo_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newsandpromotions',
            name='title_news_or_promo_ru',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newsandpromotions',
            name='title_news_or_promo_uk',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
