# Generated by Django 3.2 on 2022-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
