# Generated by Django 3.2 on 2022-12-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_contactcell_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcell',
            name='main_image',
        ),
    ]
